language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install mock
  - pip install coveralls
  - pip install .

script:
  nosetests --with-coverage --cover-package=depman

after_success:
  coveralls